networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

services:
  clarityapi:
    environment:
      - ConnectionStrings__ClarityDbContext=${ConnectionStrings__ClarityDbContext}
      - JwtOptions__SecretKey=${JwtOptions__SecretKey}
      - JwtOptions__Issuer=${JwtOptions__Issuer}
      - JwtOptions__Audience=${JwtOptions__Audience}
      - JwtOptions__ExpiresMinutes=${JwtOptions__ExpiresMinutes}
      - JwtOptions__AuthCookieName=${JwtOptions__AuthCookieName}
      - JwtOptions__RefreshCookieName=${JwtOptions__RefreshCookieName}
      - FrontendUrl=${FrontendUrl}
    build:
      context: ./backend
      dockerfile: ./Clarity.Api/Dockerfile
    networks: 
    - frontend
    - backend
    ports:
      - "333:8080"
    depends_on:
      claritydb:
        condition: service_healthy
    
  clarityfront:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - "3000:80"
    depends_on:
      - clarityapi
    
  claritydb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: elestio/pgadmin:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 8082
    networks:
      - backend
    ports:
    - "222:8082"
    depends_on:
      claritydb:
        condition: service_healthy