services:
  clarity.api:
    image: clarity.api
    environment:
      - ConnectionStrings__ClarityDbContext=${ConnectionStrings__ClarityDbContext}
      - JwtOptions__SecretKey=${JwtOptions__SecretKey}
      - JwtOptions__Issuer=${JwtOptions__Issuer}
      - JwtOptions__Audience=${JwtOptions__Audience}
      - JwtOptions__ExpiresMinutes=${JwtOptions__ExpiresMinutes}
      - JwtOptions__AuthCookieName=${JwtOptions__AuthCookieName}
      - JwtOptions__RefreshCookieName=${JwtOptions__RefreshCookieName}
      - FrontendUrl=${FrontendUrl}
    build:
      context: .
      dockerfile: Clarity.Api/Dockerfile
    ports:
      - "333:8080"
    depends_on:
      clarity.db:
        condition: service_healthy
    
      
  clarity.db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: