name: Default CI

env:
  DOTNET_VERSION: '9.0.x'
  WORKING_DIRECTORY: './backend'

on:
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ConnectionStrings__ClarityDbContext: ${{ secrets.DB_CONNECTION_STRING }}
      JwtOptions__SecretKey: ${{ secrets.JWT_SECRET_KEY }}
      JwtOptions__Issuer: "self"
      JwtOptions__Audience: "account"
      JwtOptions__ExpiresMinutes: "30"
      JwtOptions__AuthCookieName: ".AspNetCore.Application.Id"
      JwtOptions__RefreshCookieName: ".AspNetCore.Application.Name"
      FrontendUrl: ${{ secrets.FRONTEND_URL }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.WORKING_DIRECTORY }}